syntax = "proto3";

package azdext;

option go_package = "github.com/azure/azure-dev/cli/azd/pkg/azdext/gen;azdext";

import "models.proto";

service PromptService {
  rpc PromptSubscription (PromptSubscriptionRequest) returns (PromptSubscriptionResponse);
  rpc PromptLocation (PromptLocationRequest) returns (PromptLocationResponse);
  rpc PromptResourceGroup (PromptResourceGroupRequest) returns (PromptResourceGroupResponse);
}

message PromptSubscriptionRequest {}

message PromptSubscriptionResponse {
  Subscription subscription = 1;
}

message PromptLocationRequest {
  AzureContext azure_context = 1;
}

message PromptLocationResponse {
  Location location = 1;
}

message PromptResourceGroupRequest {
  AzureContext azure_context = 1;
}

message PromptResourceGroupResponse {
  ResourceGroup resource_group = 1;
}
