// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: prompt.proto

package azdext

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromptService_PromptSubscription_FullMethodName  = "/azdext.PromptService/PromptSubscription"
	PromptService_PromptLocation_FullMethodName      = "/azdext.PromptService/PromptLocation"
	PromptService_PromptResourceGroup_FullMethodName = "/azdext.PromptService/PromptResourceGroup"
)

// PromptServiceClient is the client API for PromptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptServiceClient interface {
	PromptSubscription(ctx context.Context, in *PromptSubscriptionRequest, opts ...grpc.CallOption) (*PromptSubscriptionResponse, error)
	PromptLocation(ctx context.Context, in *PromptLocationRequest, opts ...grpc.CallOption) (*PromptLocationResponse, error)
	PromptResourceGroup(ctx context.Context, in *PromptResourceGroupRequest, opts ...grpc.CallOption) (*PromptResourceGroupResponse, error)
}

type promptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptServiceClient(cc grpc.ClientConnInterface) PromptServiceClient {
	return &promptServiceClient{cc}
}

func (c *promptServiceClient) PromptSubscription(ctx context.Context, in *PromptSubscriptionRequest, opts ...grpc.CallOption) (*PromptSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptSubscriptionResponse)
	err := c.cc.Invoke(ctx, PromptService_PromptSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) PromptLocation(ctx context.Context, in *PromptLocationRequest, opts ...grpc.CallOption) (*PromptLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptLocationResponse)
	err := c.cc.Invoke(ctx, PromptService_PromptLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) PromptResourceGroup(ctx context.Context, in *PromptResourceGroupRequest, opts ...grpc.CallOption) (*PromptResourceGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptResourceGroupResponse)
	err := c.cc.Invoke(ctx, PromptService_PromptResourceGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptServiceServer is the server API for PromptService service.
// All implementations must embed UnimplementedPromptServiceServer
// for forward compatibility.
type PromptServiceServer interface {
	PromptSubscription(context.Context, *PromptSubscriptionRequest) (*PromptSubscriptionResponse, error)
	PromptLocation(context.Context, *PromptLocationRequest) (*PromptLocationResponse, error)
	PromptResourceGroup(context.Context, *PromptResourceGroupRequest) (*PromptResourceGroupResponse, error)
	mustEmbedUnimplementedPromptServiceServer()
}

// UnimplementedPromptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptServiceServer struct{}

func (UnimplementedPromptServiceServer) PromptSubscription(context.Context, *PromptSubscriptionRequest) (*PromptSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromptSubscription not implemented")
}
func (UnimplementedPromptServiceServer) PromptLocation(context.Context, *PromptLocationRequest) (*PromptLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromptLocation not implemented")
}
func (UnimplementedPromptServiceServer) PromptResourceGroup(context.Context, *PromptResourceGroupRequest) (*PromptResourceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromptResourceGroup not implemented")
}
func (UnimplementedPromptServiceServer) mustEmbedUnimplementedPromptServiceServer() {}
func (UnimplementedPromptServiceServer) testEmbeddedByValue()                       {}

// UnsafePromptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptServiceServer will
// result in compilation errors.
type UnsafePromptServiceServer interface {
	mustEmbedUnimplementedPromptServiceServer()
}

func RegisterPromptServiceServer(s grpc.ServiceRegistrar, srv PromptServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromptService_ServiceDesc, srv)
}

func _PromptService_PromptSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).PromptSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_PromptSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).PromptSubscription(ctx, req.(*PromptSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_PromptLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).PromptLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_PromptLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).PromptLocation(ctx, req.(*PromptLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_PromptResourceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptResourceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).PromptResourceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_PromptResourceGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).PromptResourceGroup(ctx, req.(*PromptResourceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromptService_ServiceDesc is the grpc.ServiceDesc for PromptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "azdext.PromptService",
	HandlerType: (*PromptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PromptSubscription",
			Handler:    _PromptService_PromptSubscription_Handler,
		},
		{
			MethodName: "PromptLocation",
			Handler:    _PromptService_PromptLocation_Handler,
		},
		{
			MethodName: "PromptResourceGroup",
			Handler:    _PromptService_PromptResourceGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prompt.proto",
}
